export const sampleDemos: Record<string, () => Promise<{ default: React.FC }>> = {
    "button-basic": () => import("./button-basic"),
    "input-basic": () => import("./input-basic"),
    "checkbox-basic": () => import("./checkbox-basic"),
    "select-sample": () => import("./select-sample"),
    "textarea-sample": () => import("./textarea-sample"),
    "div-basic": () => import("./div-basic"),
    "span-basic": () => import("./span-basic"),
    "h2-basic": () => import("./h2-basic"),
    "label-basic": () => import("./label-basic"),
    "input-button": () => import("./input-button"),
    "input-email": () => import("./input-email"),
    "input-multi-type": () => import("./input-multi-type"),
    "button-advanced-click": () => import("./ButtonAdvancedClickDemo"),
    "scroll-to-view": () => import("./scroll-to-view"),
    "table-basic": () => import("./table-basic"),
    "table-advance": () => import("./table-advance"),
    "alert-basic": () => import("./alert-basic"),
    "alert-dialog": () => import("./alert-dialog"),
};
